#spring:
#  datasource:
#    url: jdbc:mysql:localhost:3306/myDB
#    username: jang
#    password: jang
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect